### PR TITLE
Compatibility with pg17 beta3

### PR DESCRIPTION
**Pull request by hughcapet**
- Remove tuplestore_donestoring() 
   It is not needed since 7.4 (https://github.com/postgres/postgres/commit/d61a361d1aef1231db61162d99b635b89c73169d and https://github.com/postgres/postgres/commit/75680c3d805e2323cd437ac567f0677fdfc7b680)
- Test against pg17 (https://github.com/postgres/postgres/commit/6ab1dbd26bbf307055d805feaaca16dc3e750d36)

### CODE REVIEW

**Comment by FxKu** [comment]
Why is the 1 row return needed now?

**Comment by hughcapet** [comment]
@FxKu https://github.com/postgres/postgres/commit/dc9f8a798307244d791b71f666f50de319799e7c

**Comment by FxKu** [comment]
Ok so for the record:
This PR adds a bool return to pg_stats_statements_reset tests because it's behavior was [changed](https://github.com/postgres/postgres/commit/dc9f8a798307244d791b71f666f50de319799e7c) to return the timestamp the reset happened. WIth `IS NOT NULL` we test if the reset worked.

**Comment by FxKu** [comment]
:+1:

**Comment by hughcapet** [comment]
IS NOT NULL is only needed because tests compare the input and output files, while reset func now returns timestamp (obviously, always different)

**Comment by hughcapet** [comment]
👍

**Pull request merged**
